name: Laravel Pint

on:
    push:
        paths:
            - '**.php'
            - 'pint.json'
jobs:
  laravel-pint:
    name: Run Laravel Pint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.6
        with:
          preset: laravel
          testMode: true
          useComposer: true
          verboseMode: true
